BEGIN; SET search_path=rmm,public;
INSERT INTO approval_role(code,name) VALUES
('PSRM','Product Safety Risk Manager'),('MORMR','Medical Office Risk Management Representative'),
('DESIGN','Design Control Representative'),('REG','Regulatory Representative'),('QUALITY','Quality Representative')
ON CONFLICT DO NOTHING;
INSERT INTO hazardous_situation_template(code,name_template,definition) VALUES
('PAT_CLIN','Patient Exposure to [HAZARD] During Clinical Use','Incident occurs during use and exposes a patient.'),
('PAT_OUT','Patient Exposure to [HAZARD] Outside Clinical Use','Incident occurs outside use and exposes a patient.'),
('CON_USE','Consumer Exposure to [HAZARD] During Use','Consumer exposure for a non-medical product.'),
('USR_CLIN','User Exposure to [HAZARD] During Clinical Use','Incident occurs during use and exposes a user other than patient.'),
('USR_OUT','User Exposure to [HAZARD] Outside Clinical Use','Incident occurs outside use and exposes a user other than patient.'),
('ENV','Environment Exposure to [HAZARD]','Environment is exposed to a hazard.'),
('PROP','Property Exposure to [HAZARD]','Property is exposed to a hazard.'),
('NONE','No Hazardous Situation','No potential for causing harm.') ON CONFLICT DO NOTHING;
INSERT INTO hazard_category(code,name) VALUES
('BIOCHEM','Biological and Chemical'),('EM','Energy-Electromagnetic'),('MECH','Energy-Mechanical'),('RAD','Energy-Radiation'),('THERM','Energy-Thermal'),('ENV','Environmental Impact'),('OPER','Operational') ON CONFLICT DO NOTHING;
INSERT INTO hazard(code,name,hazard_category_id,definition)
SELECT x.code,x.name,c.hazard_category_id,x.def FROM (VALUES
('MECH_ACOUSTIC','Acoustic Energy','MECH','Intentional or unintentional acoustic energy.'),
('MECH_EXPELLED','Expelled Parts','MECH','Unintended expulsion or release of components.'),
('MECH_SHARP','Sharp Edges, Corners, Rough Surfaces, Pointed Tips','MECH','Sharp or rough surfaces of device or accessories.'),
('MECH_VIBRATION','Vibration','MECH','Vibrational forces generated by device or accessory.'),
('BIO_FOREIGN','Foreign Materials and Particulates','BIOCHEM','Unintended physical or chemical contaminant or debris.'),
('THERM_HIGH','High Temperature','THERM','Temperature higher than expected.'),
('OPER_PRIMARY','Function / Loss of Primary Operating Function or Essential Performance Function','OPER','Loss of primary operating or essential performance function.'),
('OPER_LABEL','Data / Incorrect Labeling','OPER','Incorrect, unclear, or missing information supplied to user or patient.')) x(code,name,cat,def)
JOIN hazard_category c ON c.code=x.cat ON CONFLICT DO NOTHING;
COMMIT;
